# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    remember-me:
      key: e48612ba1fd46fa7089fe9f5085d8d164b53ffb2
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: jhipsterGradleSampleApplication
    password:
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: root
    password:
